[package]
authors = ["guillaumelagrange <lagrange.guillaume.1@gmail.com>"]
license = "MIT OR Apache-2.0"
name = "resnet-burn"
version = "0.1.0"
edition = "2021"

[features]
default = ["burn/default"]


[dependencies]
# Note: default-features = false is needed to disable std
burn = { path = "../../burn/burn", default-features = false}
serde = { version = "1.0.192", default-features = false, features = [
    "derive",
    "alloc",
] } # alloc is for no_std, derive is needed

[dev-dependencies]
burn = { path = "../../burn/burn", default-features = false} # local burn to include the with_key_remap chain fix
burn-import = {path = "../../burn/burn-import"} # local burn-import depends on the git version of candle-core
image = { version = "0.24.7", features = ["png", "jpeg"] }